/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppLiveRouteImport } from './routes/app.live'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppRecordingsRouteImport } from './routes/app.recordings'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ClassroomClassIdRouteImport } from './routes/classroom.$classId'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherLiveRouteImport } from './routes/teacher.live'
import { Route as TeacherNotesRouteImport } from './routes/teacher.notes'
import { Route as TeacherPerformanceRouteImport } from './routes/teacher.performance'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherQuestionPapersRouteImport } from './routes/teacher.question-papers'
import { Route as TeacherRecordingsRouteImport } from './routes/teacher.recordings'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherSubjectsRouteImport } from './routes/teacher.subjects'
import { Route as TeacherTestsRouteImport } from './routes/teacher.tests'
import { Route as AppCheckoutSubjectIdRouteImport } from './routes/app.checkout.$subjectId'
import { Route as AppCoursesIndexRouteImport } from './routes/app.courses.index'
import { Route as AppCoursesSubjectIdRouteImport } from './routes/app.courses.$subjectId'
import { Route as AppSubjectsIndexRouteImport } from './routes/app.subjects.index'
import { Route as AppSubjectsSubjectIdRouteImport } from './routes/app.subjects.$subjectId'
import { Route as AppTestsIndexRouteImport } from './routes/app.tests.index'
import { Route as AppTestsTestIdRouteImport } from './routes/app.tests.$testId'
import { Route as TeacherTestsTestIdRouteImport } from './routes/teacher.tests.$testId'
import { Route as TeacherTestsNewRouteImport } from './routes/teacher.tests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordingsRoute = AppRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomClassIdRoute = ClassroomClassIdRouteImport.update({
  id: '/classroom/$classId',
  path: '/classroom/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLiveRoute = TeacherLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotesRoute = TeacherNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherPerformanceRoute = TeacherPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherQuestionPapersRoute = TeacherQuestionPapersRouteImport.update({
  id: '/question-papers',
  path: '/question-papers',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherRecordingsRoute = TeacherRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSubjectsRoute = TeacherSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestsRoute = TeacherTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => TeacherRoute,
} as any)
const AppCheckoutSubjectIdRoute = AppCheckoutSubjectIdRouteImport.update({
  id: '/checkout/$subjectId',
  path: '/checkout/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesSubjectIdRoute = AppCoursesSubjectIdRouteImport.update({
  id: '/courses/$subjectId',
  path: '/courses/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsSubjectIdRoute = AppSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsIndexRoute = AppTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => AppRoute,
} as any)
const TeacherTestsTestIdRoute = TeacherTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TeacherTestsRoute,
} as any)
const TeacherTestsNewRoute = TeacherTestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeacherTestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/live': typeof AppLiveRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/results': typeof AppResultsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classroom/$classId': typeof ClassroomClassIdRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-papers': typeof TeacherQuestionPapersRoute
  '/teacher/recordings': typeof TeacherRecordingsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/tests': typeof TeacherTestsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/app/checkout/$subjectId': typeof AppCheckoutSubjectIdRoute
  '/app/courses/$subjectId': typeof AppCoursesSubjectIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/teacher/tests/$testId': typeof TeacherTestsTestIdRoute
  '/teacher/tests/new': typeof TeacherTestsNewRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/subjects/': typeof AppSubjectsIndexRoute
  '/app/tests/': typeof AppTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/live': typeof AppLiveRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/results': typeof AppResultsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classroom/$classId': typeof ClassroomClassIdRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-papers': typeof TeacherQuestionPapersRoute
  '/teacher/recordings': typeof TeacherRecordingsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/tests': typeof TeacherTestsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/app/checkout/$subjectId': typeof AppCheckoutSubjectIdRoute
  '/app/courses/$subjectId': typeof AppCoursesSubjectIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/teacher/tests/$testId': typeof TeacherTestsTestIdRoute
  '/teacher/tests/new': typeof TeacherTestsNewRoute
  '/app/courses': typeof AppCoursesIndexRoute
  '/app/subjects': typeof AppSubjectsIndexRoute
  '/app/tests': typeof AppTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/live': typeof AppLiveRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/results': typeof AppResultsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classroom/$classId': typeof ClassroomClassIdRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-papers': typeof TeacherQuestionPapersRoute
  '/teacher/recordings': typeof TeacherRecordingsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/tests': typeof TeacherTestsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/app/checkout/$subjectId': typeof AppCheckoutSubjectIdRoute
  '/app/courses/$subjectId': typeof AppCoursesSubjectIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/teacher/tests/$testId': typeof TeacherTestsTestIdRoute
  '/teacher/tests/new': typeof TeacherTestsNewRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/subjects/': typeof AppSubjectsIndexRoute
  '/app/tests/': typeof AppTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/teacher'
    | '/verify-email'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/admin/teachers'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/live'
    | '/app/notes'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recordings'
    | '/app/results'
    | '/auth/callback'
    | '/classroom/$classId'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/live'
    | '/teacher/notes'
    | '/teacher/performance'
    | '/teacher/profile'
    | '/teacher/question-papers'
    | '/teacher/recordings'
    | '/teacher/students'
    | '/teacher/subjects'
    | '/teacher/tests'
    | '/admin/'
    | '/app/'
    | '/teacher/'
    | '/app/checkout/$subjectId'
    | '/app/courses/$subjectId'
    | '/app/subjects/$subjectId'
    | '/app/tests/$testId'
    | '/teacher/tests/$testId'
    | '/teacher/tests/new'
    | '/app/courses/'
    | '/app/subjects/'
    | '/app/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/admin/teachers'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/live'
    | '/app/notes'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recordings'
    | '/app/results'
    | '/auth/callback'
    | '/classroom/$classId'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/live'
    | '/teacher/notes'
    | '/teacher/performance'
    | '/teacher/profile'
    | '/teacher/question-papers'
    | '/teacher/recordings'
    | '/teacher/students'
    | '/teacher/subjects'
    | '/teacher/tests'
    | '/admin'
    | '/app'
    | '/teacher'
    | '/app/checkout/$subjectId'
    | '/app/courses/$subjectId'
    | '/app/subjects/$subjectId'
    | '/app/tests/$testId'
    | '/teacher/tests/$testId'
    | '/teacher/tests/new'
    | '/app/courses'
    | '/app/subjects'
    | '/app/tests'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/teacher'
    | '/verify-email'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/admin/teachers'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/live'
    | '/app/notes'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recordings'
    | '/app/results'
    | '/auth/callback'
    | '/classroom/$classId'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/live'
    | '/teacher/notes'
    | '/teacher/performance'
    | '/teacher/profile'
    | '/teacher/question-papers'
    | '/teacher/recordings'
    | '/teacher/students'
    | '/teacher/subjects'
    | '/teacher/tests'
    | '/admin/'
    | '/app/'
    | '/teacher/'
    | '/app/checkout/$subjectId'
    | '/app/courses/$subjectId'
    | '/app/subjects/$subjectId'
    | '/app/tests/$testId'
    | '/teacher/tests/$testId'
    | '/teacher/tests/new'
    | '/app/courses/'
    | '/app/subjects/'
    | '/app/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClassroomClassIdRoute: typeof ClassroomClassIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recordings': {
      id: '/app/recordings'
      path: '/recordings'
      fullPath: '/app/recordings'
      preLoaderRoute: typeof AppRecordingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom/$classId': {
      id: '/classroom/$classId'
      path: '/classroom/$classId'
      fullPath: '/classroom/$classId'
      preLoaderRoute: typeof ClassroomClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/live': {
      id: '/teacher/live'
      path: '/live'
      fullPath: '/teacher/live'
      preLoaderRoute: typeof TeacherLiveRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notes': {
      id: '/teacher/notes'
      path: '/notes'
      fullPath: '/teacher/notes'
      preLoaderRoute: typeof TeacherNotesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/performance': {
      id: '/teacher/performance'
      path: '/performance'
      fullPath: '/teacher/performance'
      preLoaderRoute: typeof TeacherPerformanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/question-papers': {
      id: '/teacher/question-papers'
      path: '/question-papers'
      fullPath: '/teacher/question-papers'
      preLoaderRoute: typeof TeacherQuestionPapersRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/recordings': {
      id: '/teacher/recordings'
      path: '/recordings'
      fullPath: '/teacher/recordings'
      preLoaderRoute: typeof TeacherRecordingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/subjects': {
      id: '/teacher/subjects'
      path: '/subjects'
      fullPath: '/teacher/subjects'
      preLoaderRoute: typeof TeacherSubjectsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/tests': {
      id: '/teacher/tests'
      path: '/tests'
      fullPath: '/teacher/tests'
      preLoaderRoute: typeof TeacherTestsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/app/checkout/$subjectId': {
      id: '/app/checkout/$subjectId'
      path: '/checkout/$subjectId'
      fullPath: '/app/checkout/$subjectId'
      preLoaderRoute: typeof AppCheckoutSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/': {
      id: '/app/courses/'
      path: '/courses'
      fullPath: '/app/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$subjectId': {
      id: '/app/courses/$subjectId'
      path: '/courses/$subjectId'
      fullPath: '/app/courses/$subjectId'
      preLoaderRoute: typeof AppCoursesSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects/': {
      id: '/app/subjects/'
      path: '/subjects'
      fullPath: '/app/subjects/'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects/$subjectId': {
      id: '/app/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId'
      preLoaderRoute: typeof AppSubjectsSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests/': {
      id: '/app/tests/'
      path: '/tests'
      fullPath: '/app/tests/'
      preLoaderRoute: typeof AppTestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests/$testId': {
      id: '/app/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/app/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/teacher/tests/$testId': {
      id: '/teacher/tests/$testId'
      path: '/$testId'
      fullPath: '/teacher/tests/$testId'
      preLoaderRoute: typeof TeacherTestsTestIdRouteImport
      parentRoute: typeof TeacherTestsRoute
    }
    '/teacher/tests/new': {
      id: '/teacher/tests/new'
      path: '/new'
      fullPath: '/teacher/tests/new'
      preLoaderRoute: typeof TeacherTestsNewRouteImport
      parentRoute: typeof TeacherTestsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppLiveRoute: typeof AppLiveRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordingsRoute: typeof AppRecordingsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCheckoutSubjectIdRoute: typeof AppCheckoutSubjectIdRoute
  AppCoursesSubjectIdRoute: typeof AppCoursesSubjectIdRoute
  AppSubjectsSubjectIdRoute: typeof AppSubjectsSubjectIdRoute
  AppTestsTestIdRoute: typeof AppTestsTestIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppLiveRoute: AppLiveRoute,
  AppNotesRoute: AppNotesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordingsRoute: AppRecordingsRoute,
  AppResultsRoute: AppResultsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCheckoutSubjectIdRoute: AppCheckoutSubjectIdRoute,
  AppCoursesSubjectIdRoute: AppCoursesSubjectIdRoute,
  AppSubjectsSubjectIdRoute: AppSubjectsSubjectIdRoute,
  AppTestsTestIdRoute: AppTestsTestIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TeacherTestsRouteChildren {
  TeacherTestsTestIdRoute: typeof TeacherTestsTestIdRoute
  TeacherTestsNewRoute: typeof TeacherTestsNewRoute
}

const TeacherTestsRouteChildren: TeacherTestsRouteChildren = {
  TeacherTestsTestIdRoute: TeacherTestsTestIdRoute,
  TeacherTestsNewRoute: TeacherTestsNewRoute,
}

const TeacherTestsRouteWithChildren = TeacherTestsRoute._addFileChildren(
  TeacherTestsRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherLiveRoute: typeof TeacherLiveRoute
  TeacherNotesRoute: typeof TeacherNotesRoute
  TeacherPerformanceRoute: typeof TeacherPerformanceRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherQuestionPapersRoute: typeof TeacherQuestionPapersRoute
  TeacherRecordingsRoute: typeof TeacherRecordingsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherSubjectsRoute: typeof TeacherSubjectsRoute
  TeacherTestsRoute: typeof TeacherTestsRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherLiveRoute: TeacherLiveRoute,
  TeacherNotesRoute: TeacherNotesRoute,
  TeacherPerformanceRoute: TeacherPerformanceRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherQuestionPapersRoute: TeacherQuestionPapersRoute,
  TeacherRecordingsRoute: TeacherRecordingsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherSubjectsRoute: TeacherSubjectsRoute,
  TeacherTestsRoute: TeacherTestsRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeacherRoute: TeacherRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClassroomClassIdRoute: ClassroomClassIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
